package com.willis.simulator

case class Rotation(name: String, piRotation: List[String], rotation: List[String])

object Rotations {

  /* rotations of interest
  1x scorch mage
  4x fireball at start regardless of PI
  2 frostbolt
  3 frostbolt
  no frostbolt
  stagger combustion
  fireblast weaving
  yes/no nightfall
  yes/no DMF
 */

  val SCORCH = "SCORCH"
  val FIREBLAST = "FIREBLAST"
  val FROSTBOLT = "FROSTBOLT"
  val FIREBALL = "FIREBALL"
  val PYROBLAST = "PYROBLAST"

  val FIRE_SPELLS = List(SCORCH, FIREBALL, FIREBLAST, PYROBLAST)

  val STANDARD = List(SCORCH, FROSTBOLT, FIREBALL)
  val FIREBALL_4 = List(SCORCH, FROSTBOLT, FIREBALL, FROSTBOLT, FIREBALL)
  val PYROBLAST_START = List(PYROBLAST, FIREBALL)

  val FROSTBOLT3 = Rotation("FROSTBOLT3", STANDARD, List(SCORCH, FROSTBOLT, FROSTBOLT, FROSTBOLT, FIREBALL))
  val FIREBALL_DROP = Rotation("FIREBALL", STANDARD, STANDARD)
  val FIREBALL_NO_DROP = Rotation("FIREBALL_NO_DROP", List(SCORCH, FIREBALL), List(SCORCH, FIREBALL))
  val FROSTBOLT2 = Rotation("FROSTBOLT2", STANDARD, List(SCORCH, FROSTBOLT, FROSTBOLT, FIREBALL))
  val FROSTBOLT2_HOLD_COMBUSTION = FROSTBOLT2.copy("FROSTBOLT2_HOLD_COMBUSTION")
  val FIREBLAST_START = Rotation("FIREBLAST_START", List(SCORCH, FIREBLAST, FIREBALL), STANDARD)
  val FIREBLAST_WEAVING = FIREBALL_DROP.copy("FIREBLAST_WEAVING")
  val STAGGER_COMBUSTION = FIREBALL_DROP.copy("STAGGER_COMBUSTION")
  val SMART_SCORCH = FIREBALL_DROP.copy("SMART_SCORCH")
  val TWO_SCORCH = FIREBALL_DROP.copy("TWO_SCORCH")
  val IMPROVED_FROSTBOLT = FROSTBOLT2.copy("IMPROVED_FROSTBOLT")
  val PYRO_START = FIREBALL_DROP.copy("PYRO_START")
  val ON_USE_VS_TEAR = FIREBALL_DROP.copy("ON_USE_VS_TEAR")
  val PRE_COMBUSTION = FIREBALL_DROP.copy("PRE_COMBUSTION")
  val SCORCH_PYRO = Rotation("SCORCH_PYRO", List(SCORCH, PYROBLAST, FIREBALL), List(SCORCH, PYROBLAST, FIREBALL))
  val FIREBALL_R11 = FIREBALL_DROP.copy("FIREBALL_R11")
  val PYRO_R11 = SCORCH_PYRO.copy("PYRO_R11")

  val STAGGER = List(STAGGER_COMBUSTION.name, SMART_SCORCH.name, TWO_SCORCH.name)
  val WEAVING = List(FIREBLAST_WEAVING.name, SMART_SCORCH.name, TWO_SCORCH.name)

  val rotations = List(FIREBALL_DROP, SMART_SCORCH, TWO_SCORCH)
  //List(FIREBALL_DROP, FIREBALL_NO_DROP, FIREBLAST_START, FIREBLAST_WEAVING, STAGGER_COMBUSTION,
  //SMART_SCORCH, TWO_SCORCH, SCORCH_PYRO, FROSTBOLT2)

}
